# Generated by Django 3.1.7 on 2021-04-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aliment1', models.CharField(max_length=30)),
                ('nutriscore1', models.IntegerField(default=-1)),
                ('aliment2', models.CharField(default='None', max_length=30)),
                ('nutriscore2', models.IntegerField(default=-1)),
                ('midi', models.BooleanField()),
                ('commentaire', models.CharField(default='None', max_length=280)),
            ],
        ),
        migrations.CreateModel(
            name='recette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=75)),
                ('rec', models.TextField(max_length=1500)),
                ('sucrée', models.BooleanField()),
            ],
        ),
    ]
